export default matches = [
    { id: 1, name: 'IMAGES', type: 'Live' },
    { id: 2, name: 'CERAMICS', type: 'Live' },
    { id: 3, name: 'SAVT20', type: 'Live' },
    { id: 11, name: 'SAAS TOURNAMENT', type: 'Live' },
    { id: 10, name: 'AC TECH BASH', type: 'Live' },
    { id: 4, name: 'AGNI', type: 'Past' },
    { id: 5, name: 'BIO-MEDICAL TOURNAMENT', type: 'Past'},
    { id: 6, name: 'MIT WORLD-CUP', type: 'Past' },
    { id: "7", name: 'TECHOFEST LEAGUE', type: 'Up',image : require('./assets/images/bg-logo.jpg') },
    { id: "8", name: 'CM TROPHY', type: 'Up' ,image : require('./assets/images/bg-logo.jpg')},
    { id: "9", name: 'CSE PREMIER LEAGUE', type: 'Up',image : require('./assets/images/bg-logo.jpg') },
    { id: "10", name: 'AGNI', type: 'Up',image : require('./assets/images/bg-logo.jpg') },
    { id: "11", name: 'CERAMICS', type: 'Up',image : require('./assets/images/bg-logo.jpg') },
  ];