export default matches = [
    { id: 1, name: 'IMAGES', type: 'Live' ,image : require('./assets/images/live1.jpg')},
    { id: 2, name: 'CERAMICS', type: 'Live',image : require('./assets/images/live2.jpg') },
    { id: 3, name: 'SAVT20', type: 'Live',image : require('./assets/images/join.jpg') },
    { id: 11, name: 'SAAS TOURNAMENT', type: 'Live' ,image : require('./assets/images/add.jpg')},
    { id: 10, name: 'AC TECH BASH', type: 'Live' ,image : require('./assets/images/view2.jpg')},
    { id: 4, name: 'AGNI', type: 'Past' ,image : require('./assets/images/past1.jpg')},
    { id: 5, name: 'BIO-MEDICAL TOURNAMENT', type: 'Past',image : require('./assets/images/past3.jpg')},
    { id: 6, name: 'MIT WORLD-CUP', type: 'Past',image : require('./assets/images/past4.jpg') },
    { id: "7", name: 'TECHOFEST LEAGUE', type: 'Up',image : require('./assets/images/jt.jpg') },
    { id: "8", name: 'CM TROPHY', type: 'Up' ,image : require('./assets/images/jt4.jpg')},
    { id: "9", name: 'CSE PREMIER LEAGUE', type: 'Up',image : require('./assets/images/jt2.jpg') },
    { id: "10", name: 'AGNI', type: 'Up',image : require('./assets/images/jt3.jpg') },
    { id: "11", name: 'CERAMICS', type: 'Up',image : require('./assets/images/jt1.jpg') },
  ];